### ISSUE TITLE
typo: in about section website link is not working

### ISSUE THREAD

**Issue by Niravprajapati1** [fairfield-programming/learn#1]
I opened website link from about section of this repository but it's not working 
![Screenshot_2022-12-29-06-19-29-32](https://user-images.githubusercontent.com/83688779/209889781-cffd6766-eae5-4cb2-8d7b-d2b1df4de9e1.jpg)

**Comment by William-McGonagle** [comment]
Oh yes sorry- the website isn't live yet, I can change that.
